#!/usr/bin/env bash
# start_all.sh — the whole system is just TWO processes now:
#   1) the UNIFIED collector  (python -m ibkr.dynamic_collector)
#        ticks -> 1sec bars + one-time 1sec catch-up backfill + L2 depth,
#        purely on-demand: nothing is collected until you search a ticker in the
#        app; the queue keeps the most-recently-searched (up to 5 tick lines /
#        3 depth lines) and evicts the oldest.
#   2) the DASH app           (python -m app, http://127.0.0.1:8050)
#
# No supervisor, no separate tick/dynamic/level2 collectors — one connection,
# one clientId (40; backfills use 41). The collector reconnects on its own.
# Prerequisites: MongoDB running on localhost:27017, and (for live data) IB
# Gateway or TWS logged in with the API enabled. The collector auto-detects the
# API port (7497 TWS paper / 4002 Gateway paper / 7496 TWS live / 4001 Gateway
# live), since both applications speak the same API and either can be pointed at
# any port. Pin one with:  python -m ibkr.dynamic_collector --port 4002
set -u
cd "$(dirname "$0")"

# Interpreter resolution, most specific first, so the repo runs on any machine:
#   1. $PYTHON            — explicit override, e.g.  PYTHON=python3.12 ./start_all.sh
#   2. an activated venv  — $VIRTUAL_ENV/bin/python
#   3. ./venv_main        — the venv this repo creates by convention
#   4. python3 on PATH
if [ -n "${PYTHON:-}" ]; then
    PY="$PYTHON"
elif [ -n "${VIRTUAL_ENV:-}" ] && [ -x "$VIRTUAL_ENV/bin/python" ]; then
    PY="$VIRTUAL_ENV/bin/python"
elif [ -x "venv_main/bin/python" ]; then
    PY="venv_main/bin/python"
else
    PY="$(command -v python3 || true)"
fi

if [ -z "$PY" ] || ! "$PY" -c "import dash" 2>/dev/null; then
    echo "ERROR: no usable Python found (tried: ${PY:-none})."
    echo "  Needs Python 3.11-3.14 with the dependencies installed:"
    echo "    python3 -m venv venv_main"
    echo "    ./venv_main/bin/pip install -r requirements.txt"
    echo "  Or point PYTHON at an interpreter that already has them:"
    echo "    PYTHON=/path/to/python ./start_all.sh"
    exit 1
fi
echo "  using interpreter: $PY  ($("$PY" -V 2>&1))"

# MongoDB is a hard prerequisite: every bar, tick and depth snapshot is read
# from and written to it, and BOTH processes below fail without it (the app
# would come up but every chart request would stall for 30s and then error).
# Check it up front so the reason is obvious instead of buried in a log.
if ! "$PY" - <<'PYCHECK' 2>/dev/null
import sys
from pymongo import MongoClient
try:
    MongoClient("mongodb://localhost:27017/",
                serverSelectionTimeoutMS=3000).admin.command("ping")
except Exception:
    sys.exit(1)
PYCHECK
then
    echo "ERROR: cannot reach MongoDB at localhost:27017."
    echo "  This project stores all candles, ticks and L2 snapshots there."
    echo "  Install and start it, then re-run:"
    echo "    macOS:  brew tap mongodb/brew && brew install mongodb-community"
    echo "            brew services start mongodb-community"
    echo "    Ubuntu: sudo apt install -y mongodb && sudo systemctl start mongodb"
    echo "    Docker: docker run -d -p 27017:27017 --name mongo mongo:7"
    exit 1
fi
echo "  MongoDB: reachable at localhost:27017"

# finviz/api_keys.py holds the FinViz Elite token and is gitignored, because
# finviz_curl.py rewrites it in place on every token renewal. A fresh clone has
# no such file, so create an empty one here. An empty token is fine — the
# dashboard runs without FinViz and simply skips consolidated-bar fetches.
if [ ! -f finviz/api_keys.py ]; then
    printf '%s\n' \
        '# Auto-generated by start_all.sh — holds the FinViz Elite API token.' \
        '# Gitignored because finviz_curl.py rewrites it on every token renewal.' \
        '# To fill it in: paste your token below, or run' \
        '#     python -m finviz.finviz_curl' \
        '# (needs FINVIZ_USERNAME / FINVIZ_PASSWORD in .env).' \
        'FINVIZ_AUTH_TOKEN = ""' \
        > finviz/api_keys.py
    echo "  created finviz/api_keys.py (empty token — FinViz bars disabled)"
fi

echo "== starting =="

# 1) Unified collector. caffeinate keeps the Mac awake for the long run.
#    Add --no-l2 to skip depth; --pin with no names for a purely on-demand set.
echo "  -> unified collector (on-demand queue, up to 5 tickers, L2 depth)"
caffeinate -i nohup "$PY" -m ibkr.dynamic_collector >> logs_collector.log 2>&1 &

# 2) Dashboard (port 8050)
echo "  -> dash app (http://127.0.0.1:8050)"
nohup "$PY" -m app >> logs_app.log 2>&1 &

sleep 5
echo "== status after start =="
ps -eo pid,command | grep -iE "ibkr\.dynamic_collector|python -m app" | grep -v grep
echo ""
echo "Logs:"
echo "  tail -f logs_collector.log   # ticks + backfill + L2 depth (everything)"
echo "  tail -f logs_app.log         # dashboard"
