#!/usr/bin/env python3
"""Start the whole system: the unified collector + the Dash app.

Cross-platform replacement for start_all.sh. The shell scripts only ever ran on
macOS/Linux (bash, caffeinate, pkill), which left Windows users with no working
entry point at all — and, worse, no access to the preflight checks below, so
they hit exactly the failures those checks exist to prevent. This launcher is
plain Python, which every user already has (it is the project's own runtime), so
there is nothing extra to install and no PowerShell execution-policy to unblock.

    python start_all.py          # start both
    python stop_all.py           # stop both

The system is TWO processes:
  1) the UNIFIED collector (python -m ibkr.dynamic_collector) — ticks -> 1sec
     bars + one-time catch-up backfill + L2 depth, purely on demand: nothing is
     collected until you search a ticker in the app.
  2) the DASH app (python -m app, http://127.0.0.1:8050)

Prerequisites: MongoDB on localhost:27017, and for live data IB Gateway or TWS
logged in with the API enabled (the collector auto-detects the port).
"""

import json
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent
PIDFILE = REPO / ".run_pids.json"
IS_WINDOWS = os.name == "nt"

COLLECTOR_CMD = ["-m", "ibkr.dynamic_collector"]
APP_CMD = ["-m", "app"]
COLLECTOR_LOG = REPO / "logs_collector.log"
APP_LOG = REPO / "logs_app.log"


def _venv_hint() -> tuple[str, str]:
    """(pip path, python path) for this platform, for error messages."""
    if IS_WINDOWS:
        return r"venv_main\Scripts\pip", r"venv_main\Scripts\python"
    return "./venv_main/bin/pip", "./venv_main/bin/python"


def check_python() -> None:
    if sys.version_info < (3, 11):
        sys.exit(
            f"ERROR: Python {sys.version_info.major}.{sys.version_info.minor} is too old.\n"
            "  This project needs Python 3.11-3.14.\n"
            "  Windows: install from https://www.python.org/downloads/ (tick\n"
            "           'Add python.exe to PATH'), then re-create the venv.\n"
            "  macOS:   brew install python@3.12"
        )


def check_dependencies() -> None:
    try:
        import dash  # noqa: F401
        import pymongo  # noqa: F401
    except ImportError as e:
        pip, py = _venv_hint()
        sys.exit(
            f"ERROR: missing dependency ({e.name}).\n"
            f"  You are running: {sys.executable}\n"
            "  Install into THIS interpreter, or activate the venv first:\n"
            f"    python -m venv venv_main\n"
            f"    {pip} install -r requirements.txt\n"
            f"    {py} start_all.py"
        )


def check_mongodb() -> None:
    """MongoDB is a hard prerequisite: every bar, tick and depth snapshot is read
    from and written to it, and BOTH processes fail without it (the app would
    come up but every chart request would stall ~30s and then error). Check it up
    front so the reason is obvious instead of buried in a log."""
    from pymongo import MongoClient
    try:
        MongoClient("mongodb://localhost:27017/",
                    serverSelectionTimeoutMS=3000).admin.command("ping")
    except Exception as e:
        install = (
            "    Windows: download the MSI from\n"
            "             https://www.mongodb.com/try/download/community\n"
            "             (it installs MongoDB as an auto-starting service), or\n"
            "             winget install MongoDB.Server\n"
            if IS_WINDOWS else
            "    macOS:  brew tap mongodb/brew && brew install mongodb-community\n"
            "            brew services start mongodb-community\n"
            "    Ubuntu: sudo apt install -y mongodb && sudo systemctl start mongodb\n"
        )
        sys.exit(
            f"ERROR: cannot reach MongoDB at localhost:27017 ({e.__class__.__name__}).\n"
            "  This project stores all candles, ticks and L2 snapshots there.\n"
            "  Install and start it, then re-run:\n"
            f"{install}"
            "    Docker: docker run -d -p 27017:27017 --name mongo mongo:7"
        )
    print("  MongoDB: reachable at localhost:27017")


def bootstrap_api_keys() -> None:
    """finviz/api_keys.py holds the FinViz Elite token and is gitignored, because
    finviz_curl.py rewrites it in place on every token renewal. A fresh clone has
    no such file, so create an empty one. An empty token is fine — the dashboard
    runs without FinViz and simply skips consolidated-bar fetches."""
    path = REPO / "finviz" / "api_keys.py"
    if path.exists():
        return
    path.write_text(
        "# Auto-generated by start_all.py — holds the FinViz Elite API token.\n"
        "# Gitignored because finviz_curl.py rewrites it on every token renewal.\n"
        "# To fill it in: paste your token below, or run\n"
        "#     python -m finviz.finviz_curl\n"
        "# (needs FINVIZ_USERNAME / FINVIZ_PASSWORD in .env).\n"
        'FINVIZ_AUTH_TOKEN = ""\n'
    )
    print("  created finviz/api_keys.py (empty token — FinViz bars disabled)")


def process_alive(pid: int) -> bool:
    """Cross-platform liveness probe.

    NOTE: os.kill(pid, 0) is NOT portable here. On Windows os.kill terminates the
    process for any signal other than CTRL_C_EVENT/CTRL_BREAK_EVENT, so the usual
    POSIX idiom would kill what it is meant to only inspect.
    """
    if IS_WINDOWS:
        out = subprocess.run(["tasklist", "/FI", f"PID eq {pid}", "/NH"],
                             capture_output=True, text=True).stdout
        return str(pid) in out
    try:
        os.kill(pid, 0)
    except (ProcessLookupError, PermissionError):
        return False
    # A terminated-but-unreaped child still answers signal 0, so signal 0 alone
    # reports zombies as alive. Ask ps for the state and treat 'Z' as dead —
    # otherwise stopping the app appears to fail whenever the parent that
    # spawned it is still around to reap it.
    state = subprocess.run(["ps", "-o", "stat=", "-p", str(pid)],
                           capture_output=True, text=True).stdout.strip()
    return bool(state) and not state.startswith("Z")


def already_running() -> dict:
    """Processes of ours that are already up, by pidfile and — on POSIX — by a
    command-line sweep as well.

    The sweep matters because the pidfile only knows about processes THIS script
    started. A collector left over from an older revision (started with nohup, or
    by hand) is invisible to it, and starting a second one silently reuses
    clientId 40: IB then has two connections fighting over the same id and
    neither collects reliably. pgrep is POSIX-only, so on Windows the pidfile is
    all we have.
    """
    found: dict[str, int] = {}
    if PIDFILE.exists():
        try:
            pids = json.loads(PIDFILE.read_text())
            found.update({name: pid for name, pid in pids.items()
                          if isinstance(pid, int) and process_alive(pid)})
        except Exception:
            pass

    if not IS_WINDOWS:
        for pattern, label in (("ibkr.dynamic_collector", "collector"),
                               ("python -m app", "app")):
            if label in found:
                continue
            out = subprocess.run(["pgrep", "-f", pattern],
                                 capture_output=True, text=True).stdout.split()
            # Ignore ourselves, in case this script's own argv matches.
            hits = [int(p) for p in out if int(p) != os.getpid()]
            if hits:
                found[f"{label} (not started by start_all.py)"] = hits[0]
    return found


def spawn(args: list[str], logfile: Path, keep_awake: bool) -> int:
    """Launch a detached background process writing to logfile."""
    cmd = [sys.executable, *args]
    # caffeinate keeps a Mac awake for long collection runs; it does not exist
    # anywhere else, so it is a macOS-only prefix rather than a requirement.
    if keep_awake and sys.platform == "darwin":
        cmd = ["caffeinate", "-i", *cmd]

    kwargs: dict = {}
    if IS_WINDOWS:
        # Detach so the processes outlive this console window.
        kwargs["creationflags"] = (subprocess.CREATE_NEW_PROCESS_GROUP
                                   | subprocess.DETACHED_PROCESS)
    else:
        kwargs["start_new_session"] = True

    log = open(logfile, "ab")
    proc = subprocess.Popen(cmd, cwd=REPO, stdout=log, stderr=subprocess.STDOUT,
                            stdin=subprocess.DEVNULL, **kwargs)
    return proc.pid


def main() -> None:
    os.chdir(REPO)
    check_python()
    check_dependencies()
    print(f"  using interpreter: {sys.executable}  (Python "
          f"{sys.version_info.major}.{sys.version_info.minor}."
          f"{sys.version_info.micro})")
    check_mongodb()
    bootstrap_api_keys()

    running = already_running()
    if running:
        listed = ", ".join(f"{n} (pid {p})" for n, p in running.items())
        sys.exit(f"ERROR: already running: {listed}.\n"
                 "  Run 'python stop_all.py' first — starting a second collector\n"
                 "  reuses clientId 40 and the two connections fight over it.")

    print("== starting ==")
    print("  -> unified collector (on-demand queue, up to 5 tickers, L2 depth)")
    collector_pid = spawn(COLLECTOR_CMD, COLLECTOR_LOG, keep_awake=True)
    print("  -> dash app (http://127.0.0.1:8050)")
    app_pid = spawn(APP_CMD, APP_LOG, keep_awake=False)

    PIDFILE.write_text(json.dumps(
        {"collector": collector_pid, "app": app_pid}, indent=2))

    print(f"\n== started ==\n  collector pid {collector_pid}\n  app       pid {app_pid}")
    print("\nOpen http://127.0.0.1:8050 and search a ticker (e.g. NVDA).")
    print("\nLogs:")
    print(f"  {COLLECTOR_LOG.name}   # ticks + backfill + L2 depth (everything)")
    print(f"  {APP_LOG.name}         # dashboard")
    print("\nStop with:  python stop_all.py")


if __name__ == "__main__":
    main()
